### ISSUE TITLE
Spiral Traversal of A matrix

### ISSUE THREAD

**Issue by Piyush228** [piyushsharma220699/Hacktoberfest-2021#11]
Adding Code with approach and problem.

Can I work on the problem titled Spiral traversal of a matrix on leetcode In C++ language?

problem link : [https://leetcode.com/problems/spiral-matrix/](url)

Please Assigned me .

**Comment by piyushsharma220699** [comment]
@Piyush228 Assigned in C++

**Comment by piyushsharma220699** [comment]
I'm closing this issue as it is already created. However it's assigned to you in C++
