### ISSUE TITLE
17. Combinations of a phone number in cpp

### ISSUE THREAD

**Issue by Samarth-Gupta-2909** [piyushsharma220699/Hacktoberfest-2021#132]
Problem Link : https://leetcode.com/problems/letter-combinations-of-a-phone-number/
Problem Number : 17

**Comment by piyushsharma220699** [comment]
@Samarth-Gupta-2909 Assigned in C++ 👍🏻

**Comment by piyushsharma220699** [comment]
@Samarth-Gupta-2909 An issue was already created for this problem, and I've assigned this problem to you there. So I'm closing this issue to remove redundancy 👍🏻
