### ISSUE TITLE
13. Roman to Integer 

### ISSUE THREAD

**Issue by khushij12** [piyushsharma220699/Hacktoberfest-2021#136]
Can you assigned this to me for C++.

**Comment by anushkarjain** [comment]
Please assign this to me in C++

**Comment by piyushsharma220699** [comment]
@khushij12 @anushkarjain Sorry :) The issue is already assigned to @Piyush228 here :: https://github.com/piyushsharma220699/Hacktoberfest-2021/issues/13

Please create an issue for another problem or check the existing issues to get them assigned to you 👍🏻 For now, I'm closing this issue.
