### ISSUE TITLE
23. Merge K Sorted Lists

### ISSUE THREAD

**Issue by sj9102001** [piyushsharma220699/Hacktoberfest-2021#156]
Can this be assigned to me in C++
Problem Link - https://leetcode.com/problems/merge-k-sorted-lists/

**Comment by piyushsharma220699** [comment]
@sj9102001 Assigned in C++

**Comment by sj9102001** [comment]
Added PR #187 Resolving this issue

**Comment by Anuradha0501** [comment]
I want to add java solution for this problem
