### ISSUE TITLE
4. Median of Two Sorted Arrays [Leetcode - Hard]

### ISSUE THREAD

**Issue by pshivesh8** [piyushsharma220699/Hacktoberfest-2021#158]
Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.

The overall run time complexity should be O(log (m+n)). 

Example:

Input: nums1 = [1,3], nums2 = [2]
Output: 2.00000
Explanation: merged array = [1,2,3] and median is 2.

Link: https://leetcode.com/problems/median-of-two-sorted-arrays/

**Comment by pshivesh8** [comment]
I want to solve this in C++, Please assign this issue to me as a part of hacktoberfest-2021

**Comment by piyushsharma220699** [comment]
Sorry, this issue is already assigned to someone else here :: https://github.com/piyushsharma220699/Hacktoberfest-2021/issues/93
I'm closing this 👍🏻
