### ISSUE TITLE
23. Merge k Sorted Lists

### ISSUE THREAD

**Issue by pshivesh8** [piyushsharma220699/Hacktoberfest-2021#160]
You are given an array of k linked-list lists, each linked-list is sorted in ascending order.
Merge all the linked lists into one sorted linked list and return it.

Example 1:

Input: lists = [[1,4,5],[1,3,4],[2,6]]
Output: [1,1,2,3,4,4,5,6]
Explanation: The linked lists are:
[
  1->4->5,
  1->3->4,
  2->6
]
merging them into one sorted list:
1->1->2->3->4->4->5->6

Link: https://leetcode.com/problems/merge-k-sorted-lists/

**Comment by pshivesh8** [comment]
I want to solve this in C++, Please assign this issue to me as a part of hacktoberfest-2021

**Comment by piyushsharma220699** [comment]
Sorry @pshivesh8 , this issue is already assigned here :: https://github.com/piyushsharma220699/Hacktoberfest-2021/issues/156
Please create an issue for some other problem 👍🏻 For now, i'll be closing this issue to avoid redundancy.
