### ISSUE TITLE
74. Search a 2D Matrix

### ISSUE THREAD

**Issue by prateeksharma2000** [piyushsharma220699/Hacktoberfest-2021#176]
Problem Link - [https://leetcode.com/problems/search-a-2d-matrix/](url)

Can I work on this problem in C++

**Comment by katariahk** [comment]
Assign this to me, I can do this in Java, Python as well as in C++ with explanation

**Comment by abhi-43** [comment]
I can solve this problem in Java with proper explanation of the approach using comments. Assign this to me

**Comment by piyushsharma220699** [comment]
Issue already present here :: https://github.com/piyushsharma220699/Hacktoberfest-2021/issues/52
Sorry @katariahk @prateeksharma2000 @abhi-43 guys, can't assign it here! Please go for some other problem :)
