### ISSUE TITLE
Starting point of loop in linked list cycle

### ISSUE THREAD

**Issue by lakhanjindam** [piyushsharma220699/Hacktoberfest-2021#214]
Assign this to me for python lang 👍

**Comment by abhi-43** [comment]
Please assign this to me in Java or C++.

**Comment by piyushsharma220699** [comment]
@lakhanjindam @abhi-43 Sorry guys, I can't understand which leetcode problem is this (please write proper name and leetcode problem number, I'll assign the issue for sure. Right now, I need to close this 👍🏻)
