### ISSUE TITLE
Longest sub-array with sum zero

### ISSUE THREAD

**Issue by lakhanjindam** [piyushsharma220699/Hacktoberfest-2021#217]
Please assign this to me in python 👍

**Comment by piyushsharma220699** [comment]
Is this problem present on leetcode? Please provide the link in description :)

**Comment by lakhanjindam** [comment]
Sorry, my bad this one is not in leetcode :( 
will update the title

**Comment by piyushsharma220699** [comment]
Create a new issue :) I'm closing this
