### ISSUE TITLE
3sum 

### ISSUE THREAD

**Issue by Haldhardwivedi** [piyushsharma220699/Hacktoberfest-2021#222]
I'm willing to solve this problem in c++ 
Link to the problem : [3SUM](https://leetcode.com/problems/3sum/)

**Comment by saigoud25** [comment]
can I solve in Java?

**Comment by piyushsharma220699** [comment]
@saigoud25 @Haldhardwivedi Issue already present here :: https://github.com/piyushsharma220699/Hacktoberfest-2021/issues/36
Please get this issue assigned to you there! For now, I'm closing this 👍🏻
