### ISSUE TITLE
4. Median of Two Sorted Arrays [Leetcode - Hard]

### ISSUE THREAD

**Issue by Lekheshwar** [piyushsharma220699/Hacktoberfest-2021#89]
Can you please assign this to me. For C++.

**Comment by piyushsharma220699** [comment]
@Lekheshwar Assigned in C++

**Comment by piyushsharma220699** [comment]
@Lekheshwar Closing this issue as I've assigned this problem here: https://github.com/piyushsharma220699/Hacktoberfest-2021/issues/93

Just to remove redundancy 👍🏻
